import { useEffect, useState } from 'react';
import { Package, Wifi, WifiOff, Search, ShieldCheck } from 'lucide-react';
import { seedDatabase } from './database/seed';
import { useProducts } from './hooks/useProducts';
import './styles/design.css';

export default function App(){
  const [ready,setReady]=useState(false); const [online,setOnline]=useState(navigator.onLine); const [query,setQuery]=useState('');
  useEffect(()=>{seedDatabase().then(()=>setReady(true)); const on=()=>setOnline(true),off=()=>setOnline(false); addEventListener('online',on);addEventListener('offline',off); return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
  const {products,loading}=useProducts(); const filtered=products.filter(p=>[p.name,p.genericName,p.sku,p.barcode].some(v=>v?.toLowerCase().includes(query.toLowerCase())));
  if(!ready||loading)return <main className="loading">Loading PharmaCare PK…</main>;
  return <div className="shell"><aside><div className="brand"><div className="brand-mark"><Package size={20}/></div><div><b>PharmaCare</b><small>PK Ecosystem</small></div></div><nav>{['Dashboard','POS','Products','Inventory','Purchases','Sales','Customers','Suppliers','Prescriptions','Accounting','Reports','Settings'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</nav><div className="offline">{online?<Wifi size={16}/>:<WifiOff size={16}/>} {online?'Online':'Offline'}<small>Local database active</small></div></aside><main className="content"><header><div><span className="eyebrow">OPERATIONS OVERVIEW</span><h1>Good morning, Owner</h1><p>Manage your pharmacy from one secure workspace.</p></div><div className="header-status"><ShieldCheck size={17}/> Offline-first enabled</div></header><section className="stats"><article><span>Products</span><strong>{products.length}</strong><small>Active catalog</small></article><article><span>Inventory status</span><strong>Ready</strong><small>Local database healthy</small></article><article><span>Connectivity</span><strong>{online?'Online':'Offline'}</strong><small>Transactions remain available</small></article><article><span>Security</span><strong>Protected</strong><small>Role-based foundation</small></article></section><section className="panel"><div className="panel-head"><div><h2>Product catalog</h2><p>Search by product, generic name, SKU, or barcode.</p></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products…" /></div></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Sale price</th><th>Tax</th><th>Status</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.genericName||'—'}</small></td><td>{p.sku}</td><td>{p.category||'Uncategorized'}</td><td>PKR {p.salePrice.toLocaleString()}</td><td>{p.taxRate}%</td><td><span className="badge">Active</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No products found. Try another search.</div>}</div></section></main></div>;
}
